---
title: "Assignment1"
author: "Lina Barbosa"
subtitle: "ESM 262"
date: "4/26/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r load packages}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggExtra)
  
})

```

```{r load data}
monthnames=data.frame(month=seq(1,12),
                      month_names=month.abb)

climate=read.table("clim.txt", header=T) %>% 
  left_join(monthnames) %>% 
  mutate(temp = (tmin+tmax)/2) 
  

```

```{r precipitation boxplot}
ggplot(data=climate, aes(x=as.factor(month), y=rain)) +
  geom_boxplot(color="darkblue") +
  stat_summary(geom="point", fun.y = "mean", color="red") +
  xlab("Month") +
  ylab("Precipitation") +
  theme_bw() +
  removeGrid(x=TRUE, y=TRUE) +
  scale_x_discrete(labels=month.abb)
```
```{r temperature boxplot}
ggplot(data=climate, aes(x = as.factor(month), y = temp)) +
  geom_boxplot(fill= "aquamarine3", color = "black") +
  stat_summary(geom="point", fun.y = "mean", color="red") +
  xlab("Month") +
  ylab("Temperature") +
  theme_bw() +
  removeGrid(x=TRUE, y=TRUE) + 
  scale_x_discrete(labels=month.abb)
```
```{r}
rain_year <- climate %>% 
  group_by(year) %>% 
  summarise(total_rain = sum(rain))

ggplot(data = rain_year, aes(x = year, y = total_rain)) + 
  geom_line(color = "gray63") +
  geom_point(color = "dodgerblue4") +
  xlab("Year") +
  ylab("Total precipitation") +
  theme_bw() +
  removeGrid(x=TRUE, y=TRUE) 
```
The driest year was `r rain_year$year[rain_year$total_rain == min(rain_year$total_rain)]` with a total precipitation of `r min(rain_year$total_rain)`. The wettest was `r rain_year$year[rain_year$total_rain == max(rain_year$total_rain)]` with a total precipitation of `r max(rain_year$total_rain)`.